#name of the workflow that will be displayed in the actions tab
name: CICD
#user will run the workflow manually whenever required
on:
  workflow_dispatch:
    inputs:
      environment: 
        description: this is the environment value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
          - 
jobs:
    code:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          run: echo "clone the code from GitHub"
          
    build:
      needs: [code]
      runs-on: ubuntu-latest
      steps:
        - name: build docker container
          run: echo "docker container build"
          
    test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - name: test the container
          run: echo "test the container"
          
    deploy:
      needs: [build, test]
      runs-on: ubuntu-latest
      steps:
        - name: deploy the application
          run: echo "docker compose deployed the app"



   
