# This is workflow name
name: Hello
# Runs on a trigger
on:
  push:
    branches: [main]
# these are jobs inside the workflow
jobs:
# this is the name of the job
  greet:
# This is github runner, each job runs on a runner
    runs-on: ubuntu-latest
    steps:
        - name: say hello to users
          run: echo "Hello Dosto"

        - name: say hello to username
          run: echo "Hello Anjali"

  details:
    runs-on: ubuntu-latest
    steps:
       - name: show the details of python and docker version 
         run: docker --version && python --version
